In [1]:
import csv
import pandas as pd

In [14]:
array=[1,2,3,0,5]
array[:-3]

[1, 2]

In [6]:
df=pd.read_csv('../AIS Sales Report 2023-04-13.csv')
df

,itemno,desc1,onhand,Jan,Feb,Mar,Apr,May,Jun,average,total
0,BLR-HC064RR-PP,"Add Description to OMS, Need Pix",0,1,466,395,322,9,282,245.833333,1475
1,EM-JAF-BK,"Add Description to OMS, Need Pix",0,0,0,0,0,0,0,0.000000,0
2,EM-JAF-BL,"Add Description to OMS, Need Pix",0,0,0,0,0,0,0,0.000000,0
3,EM-JAF-R,"Add Description to OMS, Need Pix",0,0,0,0,0,0,0,0.000000,0
4,..3PLSHIPPING,SERVICE 3RD PARTY SHIPPING LABEL,-41,15,79,69,62,7,44,46.000000,276
...,...,...,...,...,...,...,...,...,...,...,...
70117,ZDS-BLF-CCORV06ZR1,"Add Description to OMS, Need Pix",0,0,0,0,0,0,0,0.000000,0
70118,ZDS-BLF-LI300TRD,01-05 Lexus IS300 TRD Style Bumper,1,0,0,0,0,0,0,0.000000,0
70119,ZDS-BLF-SBRZ13CS,13-15 Subaru BRZ CS Style Bumper,1,0,0,0,0,0,0,0.000000,0
70120,ZDS-BLF-SFRS13CS,13-14 Scion FRS GT86 DS Style,1,0,0,0,0,0,0,0.000000,0
70121,ZDSBLF-BZ3A,"Add Description to OMS, Need Pix",0,0,0,0,0,0,0,0.000000,0